spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.file.encoding=UTF-8

# Spring Boot
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.mvc.log-resolved-exception=true

# ??? Tomcat
server.tomcat.uri-encoding=UTF-8

#spring.mvc.view.prefix=
#spring.mvc.view.suffix=
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true

# TODO Append connection to Postgres DB
#spring.datasource.driverClassName
#spring.datasource.url
#spring.datasource.username
#spring.datasource.password
